---
slug: :sub_parts_client
depends:
  mikutter: 0.2.2.1211
  plugin:
  - gtk
version: '1.1'
author: toshi_a
name: subparts client
description: 各ツイートを投稿するために使われたTwitterクライアントを表示します
repository: git://github.com/toshia/mikutter-sub-parts-client.git