---
slug: :sub_parts_client
depends:
  mikutter: "3.9.0"
  plugin:
  - gtk
version: '1.3'
author: toshi_a
name: subparts client
description: Messageを投稿するために使われたクライアントソフトウェアの名前を表示します
repository: git://github.com/toshia/mikutter-sub-parts-client.git
