---
slug: :sub_parts_client
depends:
  mikutter: "3.0.0"
  plugin:
  - gtk
version: '1.3'
author: toshi_a
name: subparts client
description: 各ツイートを投稿するために使われたTwitterクライアントを表示します
repository: git://github.com/toshia/mikutter-sub-parts-client.git
