---
slug: :sub_parts_client
depends:
  mikutter: "5.0.0"
  plugin:
  - gtk3
version: '2.0'
author: toshi_a
name: subparts client
description: Messageを投稿するために使われたクライアントソフトウェアの名前を表示します
repository: git://github.com/toshia/mikutter-sub-parts-client.git
